name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: true
      - name: CI checks
        run: ./scripts/ci.sh
      - name: Generate coverage report
        run: go test ./core/... ./cmd/krontab/... -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
